services:
  - type: web
    name: yt-proxy
    env: node
    plan: free
    buildCommand: |
      sudo apt-get update
      sudo apt-get install -y python3 python3-pip ffmpeg
      pip install yt-dlp
      yarn install
    startCommand: |
      node index.js
    envVars:
      - key: NODE_ENV
        value: production
